server:
  port: 8990


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdemo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,log4j
    logSlowSql: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    write-dates-as-timestamps: false
  #默认密码为空
  redis:
    host: localhost
    # Redis服务器连接端口
    port: 6379
    pool:
        #连接池最大连接数（使用负值表示没有限制）
      max-active: 100
        # 连接池中的最小空闲连接
      max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 100000
    # 连接超时时间（毫秒）
    timeout: 5000
    #默认是索引为0的数据库
    database: 0



pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.daitou.springbootdemo.dao
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com.daitou.springbootdemo.api.dao: debug










